#!/bin/bash -ex
# Original author: Alon Swartz <alon@turnkeylinux.org> (c) 2012-2013
# Since modified by: TurnKey Linux (c)2014-2018

# remove kernel
ARCH=$(dpkg --print-architecture)
case "$ARCH" in
    "i386")
        OLD_META_KERNEL="linux-image-686";
        ;;
    "amd64")
        OLD_META_KERNEL="linux-image-amd64";
        ;;
    *)
        fatal "non-supported architecture: $ARCH";
        ;;
esac
OLD_KERNEL=$(echo /boot/vmlinuz-* | sed 's|/boot/vmlinuz-|linux-image-|')
OLD_KERNEL_VER=$(echo /boot/vmlinuz-* | sed 's|/boot/vmlinuz-||')

mv /usr/sbin/update-grub /usr/sbin/update-grub.orig
ln -s /bin/true /usr/sbin/update-grub

debconf-set-selections << EOF
$OLD_KERNEL $OLD_KERNEL/prerm/removing-running-kernel-$OLD_KERNEL_VER boolean false
EOF
DEBIAN_FRONTEND=noninteractive apt-get -y purge $OLD_META_KERNEL $OLD_KERNEL

rm /usr/sbin/update-grub
mv /usr/sbin/update-grub.orig /usr/sbin/update-grub

# stop auto-secupdates complaining
mkdir -p /lib/modules

# remove ntp daemon
dpkg --purge ntp || true

systemctl disable confconsole

# remove /etc/fstab - workaround #1139
rm -rf /etc/fstab

# modprobe doesn't work in lxc
mv /sbin/modprobe /sbin/modprobe.orig
ln -s /bin/true /sbin/modprobe

# root password is set outside of container
chmod -x /usr/lib/inithooks/firstboot.d/30rootpass

# redirect inithook output (preseeded headless deployment)
sed -i '/REDIRECT_OUTPUT/ s/=.*/=true/g' /etc/default/inithooks

# clean up unrequired package(s)
apt autoremove -y
