#!/bin/bash -ex

invokercd=$(which invoke-rc.d)
dpkg-divert --local --rename --add $invokercd
cat>$invokercd<<'EOF'
#!/bin/sh
exit 0
EOF
chmod +x $invokercd

trap "rm $invokercd; dpkg-divert --local --rename --remove $invokercd" INT TERM EXIT

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get upgrade --autoremove -y \
    -o APT::Get::Upgrade-Allow-New \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold

INSTALLED=$(dpkg-query --showformat='${Package} ${Status}\n' -W 'linux-image-[0-9].*' | grep "ok installed" | sed 's/ .*//')
CURRENT=$(ls -l /vmlinuz | awk '{print $11}' | sed 's|boot/vmlinuz-|linux-image-|')
for KERNEL in $INSTALLED; do
    [ "$KERNEL" == "$CURRENT" ] && continue
    DEBIAN_FRONTEND=noninteractive apt-get -y purge $KERNEL
done
