#!/bin/bash -x

TOMCAT=tomcat7

CATALINA_HOME="/usr/share/$TOMCAT"
CATALINA_BASE="/var/lib/$TOMCAT"
CATALINA_TMPDIR="$CATALINA_BASE/temp"

# from https://bugs.launchpad.net/ubuntu/+source/tomcat7/+bug/1232258
create_link() {
    ln -s $CATALINA_BASE/$1 $CATALINA_HOME/$1
}
create_link common
create_link server
create_link shared
create_link conf
create_link logs
mkdir -p $CATALINA_TMPDIR
chown $TOMCAT $CATALINA_TMPDIR
