#!/bin/bash -e

info() { echo "INFO [$(basename $0)]: $@"; }
fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }

FILES=$*

set ${BT:=/turnkey/public/buildtasks}

usage() {
cat<<EOF
Syntax: $(basename $0) iso...isoN
Publish release

Options::

    --help              - display this help

Environment variables::

    BT                  - $BT

EOF
exit 1
}

if [[ "${#FILES}" < "1" ]]; then
    usage
fi

# check dependencies
[ `whoami` == 'root' ] && fatal "running as root is not supported"

export BT=$BT
export BT_CONFIG=$BT/config
. $BT/config/common.cfg

# display usage if required (cli)
[ "$USAGE" == "y" ] && usage

export NO_COPY_SSHCONF=y

for f in $FILES; do
    [ -e $f ] || fatal "$f does not exist"

    O=$(dirname $f)
    name=$(basename $f | sed 's/.iso//')
    appname=$(echo $name |sed 's/turnkey-\(.*\)-[0-9].*/\1/')
    version=$(echo $name |perl -pe 's/.*?-(\d.*)/\1/')

    export PUBLISH_DEST=${BT_PUBLISH_IMGS}/iso/
    $BT/bin/publish-files $O/$name.{iso,iso.sig}

    export PUBLISH_DEST=${BT_PUBLISH_META}/turnkey-$appname/$version/
    $BT/bin/publish-files $O/$name.{changelog,manifest,iso.sig}

    if [ -e $O/$name.tklbam/*.tar.gz ]; then
        export PUBLISH_DEST=$BT_PUBLISH_PROFILES
        $BT/bin/publish-files $O/$name.tklbam/*.tar.gz
    fi
done
