#!/bin/bash -e

fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

usage() {
cat<<EOF
Syntax: $(basename $0) [--publish] appname
Converts appliance appname (e.g., core) to ec2 ebs backed ami

Options::

    --publish           - if set, image will be made public

Environment::

    BT_VERSION          - appliance version (e.g., 11.2-lucid-x86)

    BT_DEBUG            - turn on debugging
EOF
exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        --help )     usage;;
        --publish)   publish="yes";;
        *)           if [ -n "$appname" ]; then usage; else appname=$1; fi ;;
    esac
    shift
done

[ -n "$appname" ] || usage
[ -n "$publish" ] || warning "--publish was not specified"

[ -n "$BT_DEBUG" ] && set -x

export BT=$(dirname `pwd`/$(basename $0))
export BT_CONFIG=$BT/config
. $BT_CONFIG/common.cfg
. $BT_CONFIG/build.cfg
. $BT_CONFIG/ec2.cfg

export ZONE=$(ec2metadata --availability-zone)
export REGION=$(echo -n $ZONE | head -c -1)
case "$REGION" in
    "us-east-1")
        export KERNEL=$USEAST_KERNEL
        export BUCKET=$USEAST_BUCKET
        export LOCATION="US"
        ;;
    "us-west-1")
        export KERNEL=$USWEST_KERNEL
        export BUCKET=$USWEST_BUCKET
        export LOCATION="us-west-1"
        ;;
    "eu-west-1")
        export KERNEL=$EUWEST_KERNEL
        export BUCKET=$EUWEST_BUCKET
        export LOCATION="EU"
        ;;
    "ap-southeast-1")
        export KERNEL=$APSOUTHEAST_KERNEL
        export BUCKET=$APSOUTHEAST_BUCKET
        export LOCATION="ap-southeast-1"
        ;;
    *)
        fatal "unrecognized region: $REGION"
esac

O=$BT_BUILDS/ebs
mkdir -p $O

[ -n "$BT_VERSION" ] || fatal "BT_VERSION not set"

isofile=turnkey-$appname-$BT_VERSION.iso
name=turnkey-$appname-$BT_VERSION
rootfs=$name.rootfs
cdroot=$name.cdroot

$BT/bin/iso-download $BT_ISOS $BT_VERSION $appname
$BT/bin/iso-verify $BT_ISOS $BT_VERSION $appname

cd $O
tklpatch-extract-iso $BT_ISOS/$isofile

tklpatch-apply $rootfs $BT/patches/ec2

$BT/bin/aptconf-tag $rootfs ebs

$BT/bin/ebs-bundle $rootfs $name.ebs
$BT/bin/ebs-register $name.ebs

# publish if specified
if [ "$publish" == "yes" ]; then
    $BT/bin/ebs-publish $name.ebs
fi

if [ -z "$BT_DEBUG" ] && ! (mount | grep -q $(basename $rootfs)); then
    rm -rf $rootfs
    rm -rf $cdroot
fi
