#!/bin/bash -e
# Copyright (c) 2011-2021 TurnKey GNU/Linux - http://www.turnkeylinux.org
# 
# This file is part of buildtasks.
# 
# Buildtasks is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.


fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

usage() {
cat<<EOF
Syntax: $(basename $0) [ --publish ] appname
Builds appliance appname (e.g., core) IMG

Arguments::

    appname             - e.g., core

Options::

    --publish           - publish img, release files and tklbam profile

Environment::

    BT_DEBUG            - turn on debugging
EOF
exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        --help|-h )    usage;;
        --publish)     publish="yes";;
        *)             if [ -n "$appname" ]; then usage; else appname=$1; fi ;;
    esac
    shift
done

[ -n "$appname" ] || usage
[ -n "$BT_DEBUG" ] && set -x

export BT=$(dirname $(readlink -f $0))
export BT_CONFIG=$BT/config
. $BT_CONFIG/common.cfg

if [ "$publish" == "yes" ]; then
    [ -n "$BT_PUBLISH_IMGS" ] || fatal "BT_PUBLISH_IMGS not set"
    [ -n "$BT_PUBLISH_META" ] || fatal "BT_PUBLISH_META not set"
    [ -n "$BT_PUBLISH_PROFILES" ] || fatal "BT_PUBLISH_PROFILES not set"
else
    warning "--publish was not specified"
fi

# Leverage tkldev-setup to ensure important repos are cloned and at latest
# commit; also ensures RELEASE & ARCH are set.
tkldev-setup $appname \
        || warning "tkldev-setup failed. Attempting to continue anyway."

cd $BT_PRODUCTS/$appname
deck -D build/root.sandbox || true
make clean || true
make root.sandbox || true

if [ ! -e build/root.sandbox ]; then
    if [ -z "$BT_DEBUG" ]; then
        deck -D build/root.sandbox >/dev/null 2>&1 || true
        make clean >/dev/null 2>&1 || true
    fi

    fatal "Build failed..."
fi

tklpatch-apply build/root.sandbox $BT/patches/rpi

qemu-img create -f raw build/product.img 2G
parted -s build/product.img mklabel msdos
parted -s build/product.img -- mkpart primary fat32 4MiB 400MiB
parted -s build/product.img -- mkpart primary ext2 400MiB 100%
kpartx -asv build/product.img
mkfs -t vfat -n RASPIFIRM /dev/mapper/loop0p1
mkfs -t ext4 -L RASPIROOT /dev/mapper/loop0p2
mkdir -p build/sdroot
mount /dev/mapper/loop0p2 build/sdroot
mkdir -p build/sdroot/boot/firmware
mount /dev/mapper/loop0p1 build/sdroot/boot/firmware
cp -ax build/root.sandbox/* build/sdroot
umount build/sdroot/boot/firmware
umount build/sdroot
kpartx -dsv build/product.img
xz -8 -f build/product.img

mkdir -p $BT_IMGS
$BT/bin/img-release --force $BT_IMGS

if [ "$publish" == "yes" ]; then
    name=$(cat build/root.sandbox/etc/turnkey_version)
    $BT/bin/img-publish $BT_IMGS/$name.img.xz
fi

if [ -z "$BT_DEBUG" ]; then
    deck -D build/root.sandbox
    make clean
fi
