#!/bin/bash -e

fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

usage() {
cat<<EOF
Syntax: $(basename $0) [ --publish ] appname
Builds appliance appname (e.g., core) ISO

Options::

    --publish               publish iso, release files and tklbam profile

Environment::

    BT_DEBUG                turn on debugging
EOF
exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        --help|-h )    usage;;
        --publish)     publish="yes";;
        *)             if [ -n "$appname" ]; then usage; else appname=$1; fi ;;
    esac
    shift
done

[ -n "$appname" ] || usage
[ -n "$publish" ] || warning "--publish was not specified"
[ -n "$BT_DEBUG" ] && set -x

export BT=$(dirname $(readlink -f $0))
export BT_CONFIG=$BT/config
. $BT_CONFIG/common.cfg

if [ ! -e $BT_PRODUCTS/$appname ]; then
    cd $BT_PRODUCTS
    git clone https://github.com/turnkeylinux-apps/$appname.git
    cd $BT_PRODUCTS/$appname
else
    cd $BT_PRODUCTS/$appname
    git pull
fi

deck -D build/root.tmp || true
make clean || true
make || true

if [ ! -e build/product.iso ]; then
    deck -D build/root.tmp || true
    make clean || true
    fatal "build failed..."
fi

mkdir -p $BT_ISOS
$BT/bin/iso-release --force $BT_ISOS

if [ "$publish" == "yes" ]; then
    name=$(cat build/root.patched/etc/turnkey_version)
    $BT/bin/iso-publish $BT_ISOS/$name.iso
fi

if [ -z "$BT_DEBUG" ]; then
    deck -D build/root.tmp
    make clean
fi

