#!/bin/bash -e
# Copyright (c) 2011-2015 TurnKey GNU/Linux - http://www.turnkeylinux.org
# 
# This file is part of buildtasks.
# 
# Buildtasks is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.


fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

usage() {
cat<<EOF
Syntax: $(basename $0) [--publish] appname
Perform maintenance release for appliance appname (e.g., core)

Options::

    --publish           - if set, iso and meta files will be published

Environment::

    BT_CUR_VERSION      - current appliance version (e.g., 11.1-lucid-x86)
    BT_NEW_VERSION      - new appliance version (e.g., 11.2-lucid-x86)

    BT_PUBLISH_IMGS     - publish destination for release image
    BT_PUBLISH_META     - publish destination for release meta files
    BT_PUBLISH_PROFILES - publish destination for release tklbam profile

    BT_PROFILES         - path containing tklbam profile conf files

    BT_DEBUG            - turn on debugging

Maintenance patch::

    patches/maintenance-releases/BT_NEW_VERSION

    for more details see: bin/generate-app-patch
EOF
exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        --help|-h )     usage;;
        --publish)   publish="yes";;
        *)           if [ -n "$appname" ]; then usage; else appname=$1; fi ;;
    esac
    shift
done

[ -n "$appname" ] || usage
[ -n "$publish" ] || warning "--publish was not specified"

[ -n "$BT_DEBUG" ] && set -x

export BT=$(dirname $(readlink -f $0))
export BT_CONFIG=$BT/config
. $BT_CONFIG/common.cfg
. $BT_CONFIG/build.cfg

O=$BT_BUILDS/iso
mkdir -p $O

[ -n "$BT_CUR_VERSION" ] || fatal "BT_CUR_VERSION not set"
[ -n "$BT_NEW_VERSION" ] || fatal "BT_NEW_VERSION not set"

[ -n "$BT_PROFILES" ] || fatal "BT_PROFILES not set"
export PROFILES_CONF=$BT_PROFILES

if [ "$publish" == "yes" ]; then
    [ -n "$BT_PUBLISH_IMGS" ] || fatal "BT_PUBLISH_IMGS not set"
    [ -n "$BT_PUBLISH_META" ] || fatal "BT_PUBLISH_META not set"
    [ -n "$BT_PUBLISH_PROFILES" ] || fatal "BT_PUBLISH_PROFILES not set"
fi

isofile=turnkey-$appname-$BT_CUR_VERSION.iso
curname=turnkey-$appname-$BT_CUR_VERSION
newname=turnkey-$appname-$BT_NEW_VERSION
rootfs=$curname.rootfs
cdroot=$curname.cdroot

maintenance_patch=$BT/patches/maintenance-releases/$BT_NEW_VERSION
[ -d $maintenance_patch ] || fatal "$maintenance_patch not found"

maintenance_app_patch=$O/$newname.patch
[ -d $maintenance_app_patch ] && fatal "$maintenance_app_patch already exists"

if [ ! -e "$BT_PROFILES/$appname" ]; then
    warning "$BT_PROFILES/$appname does not exist, skipping profile generation"
fi

$BT/bin/iso-download $BT_ISOS $BT_CUR_VERSION $appname
$BT/bin/iso-verify $BT_ISOS $BT_CUR_VERSION $appname

cd $O
tklpatch-extract-iso $BT_ISOS/$isofile

tklpatch-apply $rootfs $BT/patches/secupdates
tklpatch-apply $rootfs $maintenance_patch/common

$BT/bin/generate-app-patch $rootfs $maintenance_patch $maintenance_app_patch
tklpatch-apply $rootfs $maintenance_app_patch

$BT/bin/generate-manifest $rootfs > $O/$newname.manifest
cp $maintenance_app_patch/changelog $O/$newname.changelog

if [ -e "$BT_PROFILES/$appname" ]; then
    mkdir -p $O/$newname.tklbam
    $BT/bin/generate-tklbam-profile $rootfs $O/$newname.tklbam
fi

tklpatch-prepare-cdroot $rootfs $cdroot
TKLPATCH_ISOLABEL=$appname tklpatch-geniso $cdroot $O/$newname.iso

$BT/bin/generate-signature $O/$newname.iso

# hardlink iso and sig to isos (followup builds)
ln $O/$newname.iso $BT_ISOS/
ln $O/$newname.iso.sig $BT_ISOS/

# publish if specified
if [ "$publish" == "yes" ]; then
    export PUBLISH_DEST=${BT_PUBLISH_IMGS}/iso/
    $BT/bin/publish-files $O/$newname.{iso,iso.sig}

    export PUBLISH_DEST=${BT_PUBLISH_META}/turnkey-$appname/$BT_NEW_VERSION/
    $BT/bin/publish-files $O/$newname.{changelog,manifest,iso.sig}

    if [ -e "$BT_PROFILES/$appname" ]; then
        export PUBLISH_DEST=${BT_PUBLISH_PROFILES}/
        $BT/bin/publish-files $O/$newname.tklbam/*.tar.gz
    fi
fi

# cleanup unless BT_DEBUG
if [ -z "$BT_DEBUG" ] && ! (mount | grep -q $(basename $rootfs)); then
    rm -rf $rootfs
    rm -rf $cdroot
fi

