#!/bin/bash -e
# Copyright (c) 2011-2015 TurnKey GNU/Linux - http://www.turnkeylinux.org
# 
# This file is part of buildtasks.
# 
# Buildtasks is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.


fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

usage() {
cat<<EOF
Syntax: $(basename $0) appname
Wrapper script for all build targets

EOF
exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        --help|-h )  usage;;
        *)           if [ -n "$appname" ]; then usage; else appname=$1; fi ;;
    esac
    shift
done

[ -n "$appname" ] || usage

BT=$(dirname $(readlink -f $0))
ARCH=$(dpkg --print-architecture)

$BT/bt-maintenance --publish $appname
#$BT/bt-ec2 --publish --copy $appname
$BT/bt-vm --publish $appname
$BT/bt-container --publish $appname
$BT/bt-openstack --publish $appname
$BT/bt-xen --publish $appname
[ "$ARCH" == "amd64" ] && $BT/bt-docker --publish $appname

exit 0

