#!/bin/bash -e

fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

usage() {
cat<<EOF
Syntax: $(basename $0) [--publish] appname
Wrapper script for all optimized builds

Options::

    --publish           - if set, image and meta files will be published
EOF
exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        --help|-h )  usage;;
        --publish)   opts="--publish";;
        *)           if [ -n "$appname" ]; then usage; else appname=$1; fi ;;
    esac
    shift
done

[ -n "$appname" ] || usage

BT=$(dirname $(readlink -f $0))

$BT/bt-vm $opts $appname
$BT/bt-openvz $opts $appname
$BT/bt-openstack $opts $appname
$BT/bt-xen $opts $appname

