#!/bin/bash -e

fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

usage() {
cat<<EOF
Syntax: $(basename $0) [--publish --secupdates] appname
Converts appliance appname (e.g., core) to ec2 s3 backed ami

Options::

    --publish           - if set, image will be devpay'ed and made public
    --secupdates        - if set, security updates will be installed

Environment::

    BT_VERSION          - appliance version (e.g., 11.2-lucid-x86)

    BT_DEBUG            - turn on debugging
EOF
exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        --help|-h )      usage;;
        --publish)    publish="yes";;
        --secupdates) secupdates="yes";;
        *)            if [ -n "$appname" ]; then usage; else appname=$1; fi ;;
    esac
    shift
done

[ -n "$appname" ] || usage
[ -n "$publish" ] || warning "--publish was not specified"
[ -n "$secupdates" ] || warning "--secupdates was not specified"

[ -n "$BT_DEBUG" ] && set -x

export BT=$(dirname $(readlink -f $0))
export BT_CONFIG=$BT/config
. $BT_CONFIG/common.cfg
. $BT_CONFIG/build.cfg
. $BT_CONFIG/ec2.cfg

export ZONE=$(ec2metadata --availability-zone)
export REGION=$(echo -n $ZONE | head -c -1)
case "$REGION" in
    "us-east-1")
        export KERNEL=$USEAST1_KERNEL
        export BUCKET=$USEAST1_BUCKET
        export LOCATION="US"
        ;;
    "us-west-1")
        export KERNEL=$USWEST1_KERNEL
        export BUCKET=$USWEST1_BUCKET
        export LOCATION="us-west-1"
        ;;
    "us-west-2")
        export KERNEL=$USWEST2_KERNEL
        export BUCKET=$USWEST2_BUCKET
        export LOCATION="us-west-2"
        ;;
    "eu-west-1")
        export KERNEL=$EUWEST1_KERNEL
        export BUCKET=$EUWEST1_BUCKET
        export LOCATION="EU"
        ;;
    "sa-east-1")
        export KERNEL=$SAEAST1_KERNEL
        export BUCKET=$SAEAST1_BUCKET
        export LOCATION="sa-east-1"
        ;;
    "ap-southeast-1")
        export KERNEL=$APSOUTHEAST1_KERNEL
        export BUCKET=$APSOUTHEAST1_BUCKET
        export LOCATION="ap-southeast-1"
        ;;
    "ap-northeast-1")
        export KERNEL=$APNORTHEAST1_KERNEL
        export BUCKET=$APNORTHEAST1_BUCKET
        export LOCATION="ap-northeast-1"
        ;;
    *)
        fatal "unrecognized region: $REGION"
esac

O=$BT_BUILDS/s3
mkdir -p $O

[ -n "$BT_VERSION" ] || fatal "BT_VERSION not set"

isofile=turnkey-$appname-$BT_VERSION.iso
name=turnkey-$appname-$BT_VERSION
rootfs=$name.rootfs
cdroot=$name.cdroot

ami_name=$($BT/bin/ec2-uniquename $name.s3)

$BT/bin/iso-download $BT_ISOS $BT_VERSION $appname
$BT/bin/iso-verify $BT_ISOS $BT_VERSION $appname

cd $O
tklpatch-extract-iso $BT_ISOS/$isofile

tklpatch-apply $rootfs $BT/patches/cloud
tklpatch-apply $rootfs $BT/patches/ec2
[ "$secupdates" == "yes" ] && tklpatch-apply $rootfs $BT/patches/secupdates

$BT/bin/aptconf-tag $rootfs s3

$BT/bin/s3-bundle $rootfs $ami_name
$BT/bin/s3-register $ami_name.manifest.xml

# publish if specified
if [ "$publish" == "yes" ]; then
    $BT/bin/s3-publish $ami_name
fi

if [ -z "$BT_DEBUG" ] && ! (mount | grep -q $(basename $rootfs)); then
    rm -rf $rootfs
    rm -rf $cdroot
fi
