#!/bin/bash -e

fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
warning() { echo "WARNING [$(basename $0)]: $@"; }
info() { echo "INFO [$(basename $0)]: $@"; }

usage() {
cat<<EOF
Syntax: $(basename $0) [--publish] appname
Converts appliance appname (e.g., core) to vmdk and ovf

Options::

    --publish           - if set, image and meta files will be published

Environment::

    BT_VERSION          - appliance version (e.g., 11.2-lucid-x86)

    BT_PUBLISH_IMGS     - rsync destination for release image
    BT_PUBLISH_META     - rsync destination for release meta files

    BT_DEBUG            - turn on debugging
EOF
exit 1
}

while [ "$1" != "" ]; do
    case $1 in
        --help|-h )     usage;;
        --publish)   publish="yes";;
        *)           if [ -n "$appname" ]; then usage; else appname=$1; fi ;;
    esac
    shift
done

[ -n "$appname" ] || usage
[ -n "$publish" ] || warning "--publish was not specified"

[ -n "$BT_DEBUG" ] && set -x

export BT=$(dirname $(readlink -f $0))
export BT_CONFIG=$BT/config
. $BT_CONFIG/common.cfg
. $BT_CONFIG/build.cfg

O=$BT_BUILDS/vm
mkdir -p $O

[ -n "$BT_VERSION" ] || fatal "BT_VERSION not set"

if [ "$publish" == "yes" ]; then
    [ -n "$BT_PUBLISH_IMGS" ] || fatal "BT_PUBLISH_IMGS not set"
    [ -n "$BT_PUBLISH_META" ] || fatal "BT_PUBLISH_META not set"
fi

export VM_URL="http://www.turnkeylinux.org/$appname"
export VM_FULLNAME="TURNKEY $(echo $appname | tr [a-z] [A-Z] | sed s'/-/ /g')"

case "$appname" in
    canvas)           export VM_MEMORY=512 ;;
    gitlab)           export VM_MEMORY=512 ;;
    jenkins)          export VM_MEMORY=512 ;;
    clipbucket)       export VM_MEMORY=512 ;;
    moodle)           export VM_MEMORY=384 ;;
    tomcat-apache)    export VM_MEMORY=384 ;;
    appengine-java)   export VM_MEMORY=384 ;;
    *)                export VM_MEMORY=256 ;;
esac

isofile=turnkey-$appname-$BT_VERSION.iso
name=turnkey-$appname-$BT_VERSION
rootfs=$name.rootfs
cdroot=$name.cdroot

$BT/bin/iso-download $BT_ISOS $BT_VERSION $appname
$BT/bin/iso-verify $BT_ISOS $BT_VERSION $appname

cd $O
tklpatch-extract-iso $BT_ISOS/$isofile

tklpatch-apply $rootfs $BT/patches/vm

$BT/bin/aptconf-tag $rootfs vm

$BT/bin/vm-bundle $rootfs

$BT/bin/generate-signature $O/$name-vmdk.zip
$BT/bin/generate-signature $O/$name-ovf.zip

# publish if specified
if [ "$publish" == "yes" ]; then
    export PUBLISH_DEST=${BT_PUBLISH_IMGS}/vmdk/
    $BT/bin/publish-files $O/$name-vmdk.{zip,zip.sig}

    export PUBLISH_DEST=${BT_PUBLISH_IMGS}/ovf/
    $BT/bin/publish-files $O/$name-ovf.{zip,zip.sig}

    export PUBLISH_DEST=${BT_PUBLISH_META}/turnkey-$appname/$BT_VERSION/
    $BT/bin/publish-files $O/$name-vmdk.zip.sig
    $BT/bin/publish-files $O/$name-ovf.zip.sig
fi

if [ -z "$BT_DEBUG" ] && ! (mount | grep -q $(basename $rootfs)); then
    rm -rf $rootfs
    rm -rf $cdroot
fi

