#!/bin/bash -ex

install() {
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install "$@"
}

# install cloud required packages
install tkl-ec2metadata

# copy mntbind inithook in everyboot
INITHOOKS=/usr/lib/inithooks
cp $INITHOOKS/firstboot.d/27ec2-mntbind-ephemeral $INITHOOKS/everyboot.d/

# disable networking options in confconsole
sed -i "/networking false/ s|^#||" /etc/confconsole/confconsole.conf

# use ec2metadata to get public IP address
sed -i "/publicip_cmd ec2metadata/ s|^#||" /etc/confconsole/confconsole.conf

# uncomment eth1 in interfaces file (commented out in common - see #952)
sed -i "/eth1/ s|^#||" /etc/network/interfaces

# redirect inithook output (preseeded headless deployment)
sed -i '/REDIRECT_OUTPUT/ s/=.*/=true/g' /etc/default/inithooks

# ensure grub is correctly configured
bootdisk=$(find /dev -type b -name "*da")
disks=$(wc -l <<<"$bootdisk")
if [[ $disks -eq 1 ]]; then
    debconf-set-selections <<< "grub-pc grub-pc/install_devices multiselect $bootdisk"
else
    if [[ $disks -eq 0 ]]; then
        echo "FATAL: could not find bootdisk"
    else
        echo "FATAL: got multiple possibile bootdisks:" "$bootdisk"
    fi
    exit 1
fi
