#!/bin/bash -ex

# remove kernel
ARCH=$(dpkg --print-architecture)
case "$ARCH" in
    "i386")
        OLD_META_KERNEL="linux-image-686";
        ;;
    "amd64")
        OLD_META_KERNEL="linux-image-amd64";
        ;;
    *)
        fatal "non-supported architecture: $ARCH";
        ;;
esac
OLD_KERNEL=$(echo /boot/vmlinuz-* | sed 's|/boot/vmlinuz-|linux-image-|')
OLD_KERNEL_VER=$(echo /boot/vmlinuz-* | sed 's|/boot/vmlinuz-||')

mv /usr/sbin/update-grub /usr/sbin/update-grub.orig
ln -s /bin/true /usr/sbin/update-grub

debconf-set-selections << EOF
$OLD_KERNEL $OLD_KERNEL/prerm/removing-running-kernel-$OLD_KERNEL_VER boolean false
EOF
DEBIAN_FRONTEND=noninteractive apt-get -y purge $OLD_META_KERNEL $OLD_KERNEL

rm /usr/sbin/update-grub
mv /usr/sbin/update-grub.orig /usr/sbin/update-grub

# remove resolvconf
rm -rf /var/run/resolvconf
dpkg --purge resolvconf
rm -f /etc/resolv.conf*
touch /etc/resolv.conf

# remove ntp daemon
dpkg --purge ntp || true

# disable tklbam fixclock-hook - can't set time in a container (closes #1170)
chmod -x /etc/tklbam/hooks.d/fixclock

# disable confconsole
update-rc.d -f confconsole disable

# disable fgconsole (inithooks related until fixed)
mv /bin/fgconsole /bin/fgconsole.orig
ln -s /bin/false /bin/fgconsole

# modprobe doesn't work in docker
mv /sbin/modprobe /sbin/modprobe.orig
ln -s /bin/true /sbin/modprobe

# mongodb temp workaround
#  prealloc files do not contain data, but are rather simply
#  preallocated files that are ready to use that are truly preallocated
#  by the file system (i.e. they are not "sparse"). It is thus safe to
#  remove them, but if you restart mongod with journaling, it will
#  create them again if they are missing.*

[ -e /var/lib/mongodb/journal ] && rm -f /var/lib/mongodb/journal/prealloc.*

exit 0

