#!/bin/bash -ex

install() {
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

install hubclient sudo parted gdisk #ebsmount

# grub tweaks
DEFAULT=/etc/default/grub
sed -i 's/^\(GRUB_CMDLINE_LINUX_DEFAULT=.*\)"$/\1 xencons=ttyS0 console=ttyS0"/' $DEFAULT
sed -i 's/^\(GRUB_HIDDEN_TIMEOUT_QUIET=\).*$/\1true/;' $DEFAULT
sed -i 's/^\(GRUB_TIMEOUT=\).*$/\1"0"/;' $DEFAULT
sed -i 's/^#\(GRUB_DISABLE_RECOVERY\)/\1/;' $DEFAULT

# make sure images are world readable
chmod 644 /var/lib/inithooks/turnkey-init-fence/htdocs/*.png

# enable sudoadmin in rootfs
turnkey-sudoadmin on --disable-setpass

# provide for AWSMP requirment of "no default passwords"
additional_users=$(grep ":[1-9][0-9][0-9][0-9]:" /etc/passwd | cut -d: -f1)
for user in $additional_users; do
    passwd -l $user
    if [[ $user = "ansible" ]]; then
        ansible_init=/usr/lib/inithooks/firstboot.d/50ansible-key
        sed -i "/.ssh/ s|root|home/admin|" $ansible_init
    fi
done

# init fence now launches confconsole with full options, so autolaunch disabled
# on other headless builds. However, we want it on Hub builds.
confconsole_auto='/root/.bashrc.d/confconsole-auto'
[[ -f "$confconsole_auto" ]] && chmod -x "$confconsole_auto"
