#!/bin/bash -ex

update_repo() {
    apt-get update -o Dir::Etc::sourcelist="sources.list.d/$1.list" \
        -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
}

update_repo jenkins

apt-get upgrade --assume-yes

# cleanup
apt-get autoremove --assume-yes
apt-get clean
rm -f /boot/*.bak
rm -f /var/cache/apt/*.bin
rm -f /var/lib/apt/lists/pkg.*

PLUGIN=scm-api
FILE=/var/lib/jenkins/plugins/${PLUGIN}.hpi
wget -O $FILE https://updates.jenkins-ci.org/latest/${PLUGIN}.hpi
chown jenkins:jenkins $FILE

a2enmod headers
