#!/bin/sh -ex

install() {
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# install open-vm-tools and modules
KERNEL_VERSION=$(ls -l /vmlinuz | awk '{print $11}' | sed 's|boot/vmlinuz-||')
install open-vm-tools open-vm-modules-$KERNEL_VERSION
/etc/init.d/open-vm-tools stop || true

# configure sshd to permit empty passwords
sed -i 's/^PermitEmptyPasswords no/PermitEmptyPasswords yes/' /etc/ssh/sshd_config

# disable udev persistent net generation
echo -n > /etc/udev/rules.d/70-persistent-net.rules
echo -n > /lib/udev/rules.d/75-persistent-net-generator.rules

# cleanup
apt-get clean
rm -f /boot/*.bak
rm -f /var/cache/apt/*.bin
rm -f /var/lib/apt/lists/{*_Release*,*_Packages}

