#!/bin/bash -ex

install() {
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -t jessie-backports \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

apt-get -y update

# install open-vm-tools and modules
install open-vm-tools
service open-vm-tools stop || true

KERNEL_VERSION=$(ls -l /vmlinuz | awk '{print $11}' | sed 's|boot/vmlinuz-||')
MODULES_SRC=/usr/local/src/open-vm-modules/$KERNEL_VERSION.tar.gz
MODULES_DST=/lib/modules/$KERNEL_VERSION/kernel/drivers/misc/
tar -zxf $MODULES_SRC -C $MODULES_DST
rm -rf $(dirname $MODULES_SRC)
depmod -a $KERNEL_VERSION
update-initramfs -u

# disable udev persistent net generation
echo -n > /etc/udev/rules.d/70-persistent-net.rules
echo -n > /lib/udev/rules.d/75-persistent-net-generator.rules

