#!/bin/bash -ex

warn() { echo "[WARN] $0 $@" >2 ; }

install() {
    apt-get update || warn "'apt update' non zero exit code ($?) - continuing anyway..."
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# install open-vm-tools and modules
install open-vm-tools
service open-vm-tools stop || true

# disable udev persistent net generation
echo -n > /etc/udev/rules.d/70-persistent-net.rules
echo -n > /lib/udev/rules.d/75-persistent-net-generator.rules

