#!/bin/bash -e

# PVM: 'Booting paravirtualized kernel on Xen'
# HVM: 'Booting paravirtualized kernel on Xen HVM'
line=$( dmesg | grep 'Booting paravirtualized kernel on Xen' )

if echo $line | grep -q 'HVM'; then
    chmod +x /etc/grub.d/*
    chmod -x /etc/grub.d/40_custom
else
    chmod -x /etc/grub.d/*
    chmod +x /etc/grub.d/40_custom
fi

exit 0

