#!/bin/bash -e
# grow root partition and filesystem

[[ -n "$_TURNKEY_INIT" ]] && exit 0

ROOT_PART="$(findfs PARTLABEL=rootfs)"
ROOT_DEV="$(lsblk -pno PKNAME "$ROOT_PART")"

ROOT_PART_NUM="${ROOT_PART/#${ROOT_DEV}}"
ROOT_PART_NUM="${ROOT_PART_NUM/p}"

echo "Checking if root partition #$ROOT_PART_NUM ($ROOT_PART) on $ROOT_DEV can be grown..."
if growpart -N "$ROOT_DEV" "$ROOT_PART_NUM"; then
  echo "Growing root partition #$ROOT_PART_NUM ($ROOT_PART) on $ROOT_DEV..."
  growpart "$ROOT_DEV" "$ROOT_PART_NUM"

  echo "Growing root FS on $ROOT_PART..."
  resize2fs "$ROOT_PART"
fi
