#!/usr/bin/python3
# Author: Alon Swartz <alon@turnkeylinux.org>

import os
import sys

if '_TURNKEY_INIT' in os.environ:
    sys.exit(0)

import stat
import tempfile
import subprocess


def get_mounts(mounts_file="/proc/mounts"):
    """
    Given a mounts file (e.g., /proc/mounts), generate dicts with the
    following keys:

     - device: The device file which is mounted.
     - mount-point: The path at which the filesystem is mounted.
     - filesystem: The filesystem type.
     - total-space: The capacity of the filesystem in kbytes.
    """
    with open(mounts_file) as fob:
        for line in fob.readlines():
            try:
                device, mount_point, filesystem = line.split()[:3]
            except ValueError:
                continue

            stats = os.statvfs(mount_point)
            total_space = (stats.f_blocks * stats.f_bsize) / 1024

            yield {"device": device,
                   "mount-point": mount_point,
                   "filesystem": filesystem,
                   "total-space": int(total_space)}


def get_partitions(partitions_file="/proc/partitions"):
    """
    Given a partitions file (e.g., /proc/partitions), generate dicts with the
    following keys:

     - major: Major block
     - minor: Minor block
     - blocks: Amount of blocks
     - name: Partition name
    """
    with open(partitions_file) as fob:
        for line in fob.readlines():

            try:
                major, minor, blocks, name = line.split()
                blocks = int(blocks)
            except ValueError:
                continue

            yield {"major": major,
                   "minor": minor,
                   "blocks": blocks,
                   "name": name}


class RootFSError(Exception):
    pass


class RootFS:

    RootFSError = RootFSError
    SUPPORTED_FILESYSTEMS = ('ext2', 'ext3', 'ext4')

    def __init__(self, mountpoint):
        self.mountpoint = mountpoint

        m = self._get_mount(self.mountpoint)
        self.device = m['device']
        self.filesystem = m['filesystem']
        self.filesystem_size = float(m['total-space'])

        p = self._get_partition(self.device)
        self.partition_size = float(p['blocks'])

        self.fs_gb = round(self.filesystem_size / (1024 * 1024))
        self.pt_gb = round(self.partition_size / (1024 * 1024))

    @staticmethod
    def _get_mount(mountpoint):
        for m in get_mounts():
            if (m['device'].startswith('/dev/') and
                    m['mount-point'] == mountpoint):
                return m

    @staticmethod
    def _get_partition(device_name):
        for p in get_partitions():
            if p['name'] == device_name.replace('/dev/', ''):
                return p

    @property
    def has_unused_space(self):
        return True if self.pt_gb > self.fs_gb else False

    @property
    def has_supported_filesystem(self):
        if self.filesystem in self.SUPPORTED_FILESYSTEMS:
            return True
        return False

    def resize_filesystem(self):
        fd, devpath = tempfile.mkstemp(dir=self.mountpoint)
        os.unlink(devpath)
        os.close(fd)

        st_dev = os.stat(self.mountpoint).st_dev
        dev = os.makedev(os.major(st_dev), os.minor(st_dev))
        os.mknod(devpath, 0o400 | stat.S_IFBLK, dev)

        resize = subprocess.run(["resize2fs", devpath],
                                capture_output=True, text=True)
        os.unlink(devpath)
        if resize.returncode != 0:
            raise RootFSError(f"Failed to resize '{devpath}'")


def main():
    rootfs = RootFS(mountpoint="/")
    if rootfs.has_unused_space and rootfs.has_supported_filesystem:
        print(f"Resizing {rootfs.device}: {rootfs.fs_gb}G to {rootfs.pt_gb}G")
        rootfs.resize_filesystem()


if __name__ == "__main__":
    main()
