#!/bin/bash -e
# mount bind /tmp to /mnt/tmp (ephemeral storage)

[ -d /mnt/tmp ] && exit 0

mkdir -p /mnt/tmp
chmod 777 /mnt/tmp/
chmod o+t /mnt/tmp/
cp -ar /tmp/* /mnt/tmp/
echo "/mnt/tmp /tmp bind bind 0 0" >> /etc/fstab
mount /tmp

