#!/bin/bash -e

[ -n "$_TURNKEY_INIT" ] && exit 0

if grep -q SERVERID= /var/lib/hubclient/server.conf >/dev/null 2>&1; then
    # hub launch, disable sudoadmin
    sed -i "s/^SUDOADMIN=.*/SUDOADMIN=false/" /etc/default/inithooks
else
    # non-hub launch
    exit 0
fi

