#!/bin/bash -e

[ -n "$_TURNKEY_INIT" ] && exit 0

# exit if server is registered with hub
grep -q SERVERID= /var/lib/hubclient/server.conf >/dev/null 2>&1 && exit 0

# non-hub launch, enable turnkey-sudoadmin
sed -i "s/^SUDOADMIN=.*/SUDOADMIN=true/" /etc/default/inithooks

