#!/bin/bash -e

# if registered with hub, add hub tag
if grep SERVERID= /var/lib/hubclient/server.conf -q -s; then
    sed -i "s|turnkey-\(.*\))|turnkey-\1 hub)|" /etc/apt/apt.conf.d/01turnkey
fi

exit 0

