#!/bin/bash -e

aptconf_tag() {
    grep -q $1 /etc/apt/apt.conf.d/01turnkey && return
    sed -i "s|turnkey-\(.*\))|turnkey-\1 $1)|" /etc/apt/apt.conf.d/01turnkey
}

grep SERVERID= /var/lib/hubclient/server.conf -q -s && aptconf_tag hub
[ "$(ec2metadata --product-codes)" == "unavailable" ] || aptconf_tag mp

exit 0

