#!/bin/bash

[ -n "$_TURNKEY_INIT" ] && exit 0

. /etc/default/inithooks
[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

[ -z $RESTORE_BACKUPID ] && exit 0

hubclient-status tklbam-restore
tklbam-restore --noninteractive $RESTORE_BACKUPID

