#!/bin/bash -e
# set root password (unless already set OOB)

. /etc/default/inithooks

if grep -qs ^root:U6aMy0wojraho /etc/shadow; then
    [ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
    $INITHOOKS_PATH/bin/setpass.py root --pass="$ROOT_PASS"
fi

exit 0

