#!/bin/bash -ex

export DEBIAN_FRONTEND=noninteractive
_apt() {
    opts="-o DPkg::Options::=--force-confdef -o DPkg::Options::=--force-confold"
    cmd=$1
    shift
    case $cmd in
        install)    args="-y $opts";;
        reinstall)  cmd=install
                    args="--reinstall -y $opts";;
        remove)     args="-y";;
    esac
    apt-get $cmd $args "$@"
}

list_file=/var/lib/apt/lists/archive.turnkeylinux.org_debian_dists_bullseye_Release
[[ -f "$list_file" ]] || apt-get update

_apt remove live-tools
_apt reinstall initramfs-tools
# di-live was also removed above and will reinstall live-tools
_apt install di-live
