#!/bin/bash -ex

# grub tweaks
chmod -x /etc/grub.d/*
chmod +x /etc/grub.d/40_custom
update-grub
ln -sf /boot/grub/grub.cfg /boot/grub/menu.lst

# disable confconsole init script
update-rc.d -f confconsole disable

# redirect inithook output (preseeded headless deployment)
sed -i '/REDIRECT_OUTPUT/ s/=.*/=true/g' /etc/default/inithooks

