#!/bin/sh -ex

install() {
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# link update-grub to update-grub-legacy-ec2
mv /usr/sbin/update-grub /usr/sbin/update-grub.orig
ln -s /usr/sbin/update-grub-legacy-ec2 /usr/sbin/update-grub

# install required packages
install linux-image-xen-686 libc6-xen

# remove packages we don't need (eg. generic kernel)
dpkg --purge $(dpkg-query --showformat='${Package}\n' -W '*-686' | grep -v xen)

# fix grub
sed -i 's|root=/dev/hda1|root=/dev/xvda1|' /boot/grub/menu.lst
sed -i 's| console=hvc0| xencons=hvc0 console=hvc0|' /boot/grub/menu.lst
update-grub-legacy-ec2

# disable confconsole init script
update-rc.d -f confconsole disable

# redirect inithook output (preseeded headless deployment)
sed -i '/REDIRECT_OUTPUT/ s/=.*/=true/g' /etc/default/inithooks

