#!/bin/bash -ex

# create grub config for pvgrub
chmod -x /etc/grub.d/??_*
chmod +x /etc/grub.d/40_custom
grub-mkconfig -o /boot/grub/menu.lst

# disable pvgrub, ebs-bundle will handle grub config for hvm
# inithooks/firstboot.d/??ec2-pvmshim will revert if pvm
chmod +x /etc/grub.d/??_*
chmod -x /etc/grub.d/40_custom
