#!/bin/sh -ex

install() {
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# install required packages
install quota

# remove kernel
mv /usr/sbin/update-grub /usr/sbin/update-grub.orig
ln -s /bin/true /usr/sbin/update-grub
dpkg --purge $(dpkg-query --showformat='${Package}\n' -W '*-686')
rm /usr/sbin/update-grub
mv /usr/sbin/update-grub.orig /usr/sbin/update-grub

# remove resolvconf
rm -rf /var/run/resolvconf
dpkg --purge resolvconf
rm -f /etc/resolv.conf*
touch /etc/resolv.conf

# remove ntp daemon
dpkg --purge ntp

# disable ttys
sed -i '/^[^#]:[2-5]*:respawn:*/s/^/# /' /etc/inittab

update-rc.d -f confconsole disable

# modprobe doesn't work in openvz
mv /sbin/modprobe /sbin/modprobe.orig
ln -s /bin/true /sbin/modprobe

# root password is set outside of container
chmod -x /usr/lib/inithooks/firstboot.d/30rootpass

# redirect inithook output (preseeded headless deployment)
sed -i '/REDIRECT_OUTPUT/ s/=.*/=true/g' /etc/default/inithooks

# cleanup
apt-get clean
rm -f /boot/*.bak
rm -f /var/cache/apt/*.bin
rm -f /var/lib/apt/lists/{*_Release*,*_Packages}

