#!/bin/bash -e

[ -n "$_TURNKEY_INIT" ] && exit 0

aptconf_tag() {
    grep -q $1 /etc/apt/apt.conf.d/01turnkey && return
    sed -i "s|turnkey-\(.*\))|turnkey-\1 $1)|" /etc/apt/apt.conf.d/01turnkey
}

if ec2metadata --kernel-id |grep -q aki; then
    chmod -x /etc/grub.d/*
    chmod +x /etc/grub.d/40_custom
    aptconf_tag pvm
else
    chmod +x /etc/grub.d/*
    chmod -x /etc/grub.d/40_custom
    aptconf_tag hvm
fi

exit 0
