#!/usr/bin/python3
# Author: Alon Swartz <alon@turnkeylinux.org>

import os
import sys

if '_TURNKEY_INIT' in os.environ:
    sys.exit(0)

import tempfile
import subprocess

import ec2metadata


def main():
    userdata = ec2metadata.get('user-data')

    if userdata and userdata.startswith("#!"):
        with tempfile.NamedTemporaryFile("w", prefix="ec2userdata") as fob:
            fob.writelines(userdata)
            os.chmod(fob.name, 0o750)
            subprocess.run([fob.name])
            print("# executed ec2 user-data script")

if __name__ == "__main__":
    main()
