#!/bin/bash -e
# mount bind various directories to ephemeral storage

DIRS="/tmp /var/cache/tklbam"

for dir in $DIRS; do
    # skip if already mounted
    findmnt -l $dir >/dev/null && continue
    mkdir -p /mnt$dir
    rsync -aq $dir/ /mnt$dir
    mount --bind /mnt$dir $dir
done

