#!/usr/bin/python
# Author: Alon Swartz <alon@turnkeylinux.org>

import os
import ec2metadata

def authorize_sshkeys(keys, homedir):
    sshdir = os.path.join(homedir, '.ssh')
    if not os.path.exists(sshdir):
        os.makedirs(sshdir)
        os.chmod(sshdir, 0700)

    f = open(os.path.join(sshdir, 'authorized_keys'), 'a')
    f.write(''.join(['%s\n' % key for key in keys]))
    f.close()

def main():
    keys = ec2metadata.get('public-keys')
    if keys:
        authorize_sshkeys(keys, '/root')


if __name__ == "__main__":
    main()

