#!/bin/bash

USERNAME=root

. /etc/default/inithooks
[ "$(echo $SUDOADMIN | tr [A-Z] [a-z] )" = "true" ] && USERNAME=admin

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# Display root password just incase user can't use ssh key to login
echo
echo "################################## [ LOGIN DETAILS ] ###################################"
echo
echo "                        Random initial $USERNAME password: $ROOT_PASS"
echo "########################################################################################"
echo
