#!/bin/sh

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# Display root password just incase user can't use ssh key to login
echo
echo "################################## [ LOGIN DETAILS ] ###################################"
echo
echo "                        Random initial root password: $ROOT_PASS"
echo "########################################################################################"
echo
