#!/bin/bash

[ -n "$_TURNKEY_INIT" ] && exit 0

USERNAME=root

. /etc/default/inithooks
[ "$(echo $SUDOADMIN | tr [A-Z] [a-z] )" = "true" ] && USERNAME=admin

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# Display root password just incase user can't use ssh key to login
echo
echo "################################## [ LOGIN DETAILS ] ###################################"
echo
echo "                        Random initial $USERNAME password: $ROOT_PASS"
echo
echo "########################################################################################"

## print ssh hostkey fingerprints now, otherwise they only show up after security updates are installed
echo
/usr/lib/inithooks/everyboot.d/70ec2-log-sshfp
