#!/bin/bash

[ -n "$_TURNKEY_INIT" ] && exit 0

. /etc/default/inithooks

for USERNAME in root `ls /home`; do
  PROFILE_FIRSTLOGIN=$(eval printf ~$USERNAME)/.profile.d/turnkey-init-fence
  [ -f $PROFILE_FIRSTLOGIN ] && chmod +x $PROFILE_FIRSTLOGIN
done

update-rc.d turnkey-init-fence defaults
/etc/init.d/turnkey-init-fence start
echo 'turnkey-init-fence is up'
