#!/bin/bash -e
# generic preseeding of inithooks.conf if it doesn't exist

[ -e $INITHOOKS_CONF ] && exit 0

#MASTERPASS=$(mcookie | cut --bytes 1-8)
MASTERPASS=turnkey

cat>$INITHOOKS_CONF<<EOF
export ROOT_PASS=$MASTERPASS
export DB_PASS=$MASTERPASS
export APP_PASS=$MASTERPASS
export APP_EMAIL=admin@example.com
export APP_DOMAIN=DEFAULT
export HUB_APIKEY=SKIP
export SEC_UPDATES=FORCE
EOF

