#!/bin/bash -ex

invokercd=$(which invoke-rc.d)
dpkg-divert --local --rename --add $invokercd
cat>$invokercd<<'EOF'
#!/bin/sh
exit 0
EOF
chmod +x $invokercd

trap "rm $invokercd; dpkg-divert --local --rename --remove $invokercd" INT TERM EXIT

for actionfile in /etc/cron-apt/action.d/*; do
    while read aptcmd; do
        aptcmd=$(echo $aptcmd | sed "s|-q||")
        aptcmd=$(echo $aptcmd | sed "s|-o quiet=.*||")
        DEBIAN_FRONTEND=noninteractive apt-get $aptcmd
    done < $actionfile
done

INSTALLED=$(dpkg-query --showformat='${Package} ${Status}\n' -W 'linux-image-[0-9].*' | grep "ok installed" | sed 's/ .*//')
CURRENT=$(ls -l /vmlinuz | awk '{print $11}' | sed 's|boot/vmlinuz-|linux-image-|')
for KERNEL in $INSTALLED; do
    [ "$KERNEL" == "$CURRENT" ] && continue
    DEBIAN_FRONTEND=noninteractive apt-get -y purge $KERNEL
done
